[package]
name = "sah"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3.7"
html-escape = "0.2.13"
serde_json = "1"
text-to-png = "0.2.0"
uuid = { version = "1.17.0", features = ["v7"] }
cookie = "0.18.1"
url = "2.5.4"
