[package]
name = "brs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
clap = { version = "4.5.21", features = ["derive"] }
serde_json = "1"
